#*********************************************************************
# Copyright (c) Intel Corporation 2020
# SPDX-License-Identifier: Apache-2.0
#*********************************************************************/

FROM node:latest

COPY tmp-git-pass /.ci/.gitpsw

RUN apt-get update && apt-get install -y git \
  && git config --global credential.username github-rsd-service \
  && git config --global credential.helper "!echo password=\$(cat /.ci/.gitpsw); echo"
