#/*********************************************************************
# Copyright (c) Intel Corporation 2020
# SPDX-License-Identifier: Apache-2.0
#**********************************************************************/
version: '3.3'
services: 
  rps:
    image: ${RPS_IMAGE}
    ports: 
      - "${RPS_WEBSOCKETPORT}:${RPS_WEBSOCKETPORT}"
      - "${RPS_WEB_PORT}:${RPS_WEB_PORT}"
    depends_on:
      - mps
    environment: 
      RPS_USE_VAULT: ${RPS_USE_VAULT}
      RPS_NODE_ENV: ${RPS_NODE_ENV}
      RPS_HTTPS: ${RPS_HTTPS}
      RPS_USE_DB_PROFILES: ${RPS_USE_DB_PROFILES}
      RPS_DB_HOST: ${RPS_DB_HOST}
      RPS_DB_NAME: ${RPS_DB_NAME}
      RPS_DB_PORT: ${RPS_DB_PORT}
      RPS_DB_USER: ${RPS_DB_USER}
      RPS_DB_PASSWORD: ${RPS_DB_PASSWORD}
      RPS_WEBSOCKETTLS: ${RPS_WEBSOCKETTLS}
      RPS_WEB_PORT: ${RPS_WEB_PORT}
      RPS_WEBSOCKETPORT: ${RPS_WEBSOCKETPORT}
      RPS_XAPIKEY: ${RPS_XAPIKEY}
      RPS_VAULT_ADDRESS: ${RPS_VAULT_ADDRESS}
      RPS_VAULT_TOKEN: ${RPS_VAULT_TOKEN}
      RPS_SECRETS_PATH: ${RPS_SECRETS_PATH}
      RPS_CREDENTIALS_PATH: ${RPS_CREDENTIALS_PATH}
      RPS_USER: ${RPS_MPS_USER}
      RPS_PASSWORD: ${RPS_MPS_PASSWORD}
      RPS_AMT_USER: ${RPS_AMT_USER}
      RPS_WEB_TLS_CERT: ${RPS_WEB_TLS_CERT}
      RPS_WEB_TLS_CERT_KEY: ${RPS_WEB_TLS_CERT_KEY}
      RPS_ROOT_CA_CERT: ${RPS_ROOT_CA_CERT}
      RPS_LOG_LEVEL: ${RPS_LOG_LEVEL}
    volumes:
      - private-volume:/rcs-microservice/private
    command: >
      /bin/bash -c "
        while ! nc -z mps 3000;
        do
          echo waiting for mps;
          sleep 5;
        done;
        echo MPS Running!;
        npm start;
      "
  mps:
    image: ${MPS_IMAGE}
    ports: 
      - "${MPS_WEB_PORT}:${MPS_WEB_PORT}"
      - "${MPS_PORT}:${MPS_PORT}"
    environment: 
      MPS_GENERATE_CERTS: ${MPS_GENERATE_CERTS}
      MPS_COMMON_NAME: ${MPS_COMMON_NAME}
      MPS_NODE_ENV: ${MPS_NODE_ENV}
      MPS_USE_ALLOWLIST: ${MPS_USE_ALLOWLIST}
      MPS_PORT: ${MPS_PORT}
      MPS_WEB_PORT: ${MPS_WEB_PORT}
      MPS_USERNAME: ${MPS_USER}
      MPS_PASS: ${MPS_PASSWORD}
      MPS_USE_GLOBAL_CREDENTIALS: ${MPS_USE_GLOBAL_CREDENTIALS}
      MPS_ENABLE_LOGGING: ${MPS_ENABLE_LOGGING}
      MPS_DEBUG: ${MPS_DEBUG}
      MPS_USE_VAULT: ${MPS_USE_VAULT}
      MPS_VAULT_ADDRESS: ${MPS_VAULT_ADDRESS}
      MPS_VAULT_TOKEN: ${MPS_VAULT_TOKEN}
      MPS_SECRETS_PATH: ${MPS_SECRETS_PATH}
      MPS_WEB_ADMIN_USER: ${MPS_WEB_ADMIN_USER}
      MPS_WEB_ADMIN_PASSWORD: ${MPS_WEB_ADMIN_PASSWORD}
      MPS_HTTPS: ${MPS_HTTPS}
      MPS_MPSXAPIKEY: ${MPS_XAPIKEY}
      MPS_LISTEN_ANY: ${MPS_LISTEN_ANY}
      MPS_TLS_OFFLOAD: ${MPS_TLS_OFFLOAD}
      MPS_SESSION_ENCRYPTION_KEY: ${MPS_SESSION_ENCRYPTION_KEY}
      MPS_LOG_LEVEL: ${MPS_LOG_LEVEL}
      MPS_AUTH_ENABLED: ${MPS_AUTH_ENABLED}
      REACT_APP_MPS_WEB_PORT: ${MPS_WEB_PORT}
      REACT_APP_RPS_WEB_PORT: ${RPS_WEB_PORT}
      REACT_APP_RPS_SERVER: ${MPS_COMMON_NAME}
      REACT_APP_MPS_SERVER: ${MPS_COMMON_NAME}
      REACT_APP_MPSXAPIKEY: ${MPS_XAPIKEY}
      REACT_APP_RPSXAPIKEY: ${RPS_XAPIKEY}
    volumes:
      - private-volume:/mps-microservice/private
volumes:
    app-volume:
    private-volume:
